-- Created by Vertabelo (http://vertabelo.com)
-- Last modification date: 2022-08-17 19:05:22.561

-- tables
-- Table: Z_ALLERGY
CREATE TABLE Z_ALLERGY (
    ALLERGY_CODE varchar2(20)  NOT NULL,
    ALLERGY_DESCRIPTION varchar2(255)  NULL,
    CONSTRAINT Z_ALLERGY_DESCRIPTION_UK UNIQUE (ALLERGY_DESCRIPTION),
    CONSTRAINT Z_ALLERGY_pk PRIMARY KEY (ALLERGY_CODE)
) ;

-- Table: Z_BODYSITE
CREATE TABLE Z_BODYSITE (
    BODYSITE_CODE varchar2(10)  NOT NULL,
    BODYSITE_DESCRIPTION varchar2(50)  NOT NULL,
    CONSTRAINT Z_BODYSITE_DESC_UK UNIQUE (BODYSITE_DESCRIPTION),
    CONSTRAINT Z_BODYSITE_pk PRIMARY KEY (BODYSITE_CODE)
) ;

-- Table: Z_CITY
CREATE TABLE Z_CITY (
    COUNTRY_ID number(5)  NOT NULL,
    STATE_ID number(5)  NOT NULL,
    CITY_ID number(5)  NOT NULL,
    CITY_NAME varchar2(50)  NOT NULL,
    COUNTY_ID number(5)  NULL,
    CONSTRAINT Z_CITY_NAME_UK UNIQUE (COUNTRY_ID, STATE_ID, CITY_NAME),
    CONSTRAINT Z_CITY_pk PRIMARY KEY (COUNTRY_ID,STATE_ID,CITY_ID)
) ;

-- Table: Z_COUNTRY
CREATE TABLE Z_COUNTRY (
    COUNTRY_ID number(5)  NOT NULL,
    COUNTRY_NAME char(2)  NOT NULL,
    CONSTRAINT Z_COUNTRY_NAME_UK UNIQUE (COUNTRY_NAME),
    CONSTRAINT Z_COUNTRY_pk PRIMARY KEY (COUNTRY_ID)
) ;

-- Table: Z_COUNTY
CREATE TABLE Z_COUNTY (
    COUNTRY_ID number(5)  NOT NULL,
    STATE_ID number(5)  NOT NULL,
    COUNTY_ID number(5)  NOT NULL,
    COUNTY_NAME varchar2(50)  NOT NULL,
    CONSTRAINT Z_COUNTY_NAME_UK UNIQUE (COUNTRY_ID, STATE_ID, COUNTY_NAME),
    CONSTRAINT Z_COUNTY_pk PRIMARY KEY (COUNTRY_ID,STATE_ID,COUNTY_ID)
) ;

-- Table: Z_ETHNICITY
CREATE TABLE Z_ETHNICITY (
    ETHNICITY_ID number(5)  NOT NULL,
    ETHNICITY_DESCRIPTION varchar2(50)  NOT NULL,
    CONSTRAINT Z_ETHNICITY_DESC_UK UNIQUE (ETHNICITY_DESCRIPTION),
    CONSTRAINT Z_ETHNICITY_pk PRIMARY KEY (ETHNICITY_ID)
) ;

-- Table: Z_GENDER
CREATE TABLE Z_GENDER (
    GENDER_ID char(1)  NOT NULL,
    GENDER_DESCRIPTION varchar2(50)  NOT NULL,
    CONSTRAINT Z_GENDER_DESC_UK UNIQUE (GENDER_DESCRIPTION),
    CONSTRAINT Z_GENDER_pk PRIMARY KEY (GENDER_ID)
) ;

-- Table: Z_IMMUNIZATION
CREATE TABLE Z_IMMUNIZATION (
    IMMUNIZATION_CODE varchar2(5)  NOT NULL,
    IMMUNIZATION_DESCRIPTION varchar2(50)  NOT NULL,
    CONSTRAINT Z_IMMUNIZATION_DESC_UK UNIQUE (IMMUNIZATION_DESCRIPTION),
    CONSTRAINT Z_IMMUNIZATION_pk PRIMARY KEY (IMMUNIZATION_CODE)
) ;

-- Table: Z_MARITAL_STATUS
CREATE TABLE Z_MARITAL_STATUS (
    MARITAL_STATUS_ID char(1)  NOT NULL,
    MARITAL_STATUS_DESCRIPTION varchar2(50)  NOT NULL,
    CONSTRAINT Z_MARITAL_STATUS_DESC_UK UNIQUE (MARITAL_STATUS_DESCRIPTION),
    CONSTRAINT Z_MARITAL_STATUS_pk PRIMARY KEY (MARITAL_STATUS_ID)
) ;

-- Table: Z_MODALITY
CREATE TABLE Z_MODALITY (
    MODALITY_CODE char(2)  NOT NULL,
    MODALITY_DESCRIPTION varchar2(50)  NOT NULL,
    CONSTRAINT Z_MODALITY_DESC_UK UNIQUE (MODALITY_DESCRIPTION),
    CONSTRAINT Z_MODALITY_pk PRIMARY KEY (MODALITY_CODE)
) ;

-- Table: Z_PATIENT
CREATE TABLE Z_PATIENT (
    PATIENT_ID varchar2(255)  NOT NULL,
    BIRTHDATE date  NOT NULL,
    DEATHDATE date  NULL,
    SSN varchar2(50)  NOT NULL,
    DRIVERS varchar2(50)  NULL,
    PASSPORT varchar2(50)  NULL,
    PREFIX varchar2(50)  NULL,
    FIRST_NAME varchar2(50)  NOT NULL,
    LAST_NAME varchar2(50)  NOT NULL,
    SUFFIX varchar2(50)  NULL,
    MAIDEN_NAME varchar2(50)  NULL,
    MARITAL_STATUS_ID char(1)  NOT NULL,
    RACE_ID number(5)  NOT NULL,
    ETHNICITY_ID number(5)  NOT NULL,
    GENDER_ID char(1)  NOT NULL,
    HEALTHCARE_EXPENSES number(15,2)  NOT NULL,
    HEALTHCARE_COVERAGE number(15,2)  NOT NULL,
    BIRTH_PLACE_COUNTRY_ID number(5)  NOT NULL,
    BIRTH_PLACE_STATE_ID number(5)  NOT NULL,
    BIRTH_PLACE_CITY_ID number(5)  NOT NULL,
    ADDRESS varchar2(255)  NOT NULL,
    ZIP varchar2(10)  NULL,
    LIVING_PLACE_COUNTRY_ID number(5)  NOT NULL,
    LIVING_PLACE_STATE_ID number(5)  NOT NULL,
    LIVING_PLACE_CITY_ID number(5)  NOT NULL,
    CONSTRAINT Z_PATIENT_pk PRIMARY KEY (PATIENT_ID)
) ;

-- Table: Z_PATIENT_ALLERGY
CREATE TABLE Z_PATIENT_ALLERGY (
    PATIENT_ID varchar2(255)  NOT NULL,
    ALLERGY_CODE varchar2(20)  NOT NULL,
    ALLERGY_START date  NOT NULL,
    ALLERGY_STOP date  NULL,
    CONSTRAINT Z_PATIENT_ALLERGY_pk PRIMARY KEY (PATIENT_ID,ALLERGY_CODE,ALLERGY_START)
) ;

-- Table: Z_PATIENT_IMAGING_STUDY
CREATE TABLE Z_PATIENT_IMAGING_STUDY (
    IMAGING_STUDY_ID varchar2(255)  NOT NULL,
    IMAGING_STUDY_DATE date  NOT NULL,
    PATIENT_ID varchar2(255)  NOT NULL,
    BODYSITE_CODE varchar2(10)  NOT NULL,
    MODALITY_CODE char(2)  NOT NULL,
    SOP_CODE varchar2(30)  NOT NULL,
    CONSTRAINT Z_PATIENT_IMAGING_STUDY_pk PRIMARY KEY (IMAGING_STUDY_ID)
) ;

-- Table: Z_PATIENT_IMMUNIZATION
CREATE TABLE Z_PATIENT_IMMUNIZATION (
    PATIENT_ID varchar2(255)  NOT NULL,
    IMMUNIZATION_CODE varchar2(5)  NOT NULL,
    IMMUNIZATION_DATE date  NOT NULL,
    BASE_COST number(15,2)  NULL,
    CONSTRAINT Z_PATIENT_IMMUNIZATION_pk PRIMARY KEY (PATIENT_ID,IMMUNIZATION_CODE,IMMUNIZATION_DATE)
) ;

-- Table: Z_RACE
CREATE TABLE Z_RACE (
    RACE_ID number(5)  NOT NULL,
    RACE_DESCRIPTION varchar2(50)  NOT NULL,
    CONSTRAINT Z_RACE_DESC_UK UNIQUE (RACE_DESCRIPTION),
    CONSTRAINT Z_RACE_pk PRIMARY KEY (RACE_ID)
) ;

-- Table: Z_SOP
CREATE TABLE Z_SOP (
    SOP_CODE varchar2(30)  NOT NULL,
    SOP_DESCRIPTION varchar2(50)  NOT NULL,
    CONSTRAINT Z_SOP_DESC_UK UNIQUE (SOP_DESCRIPTION),
    CONSTRAINT Z_SOP_pk PRIMARY KEY (SOP_CODE)
) ;

-- Table: Z_STATE
CREATE TABLE Z_STATE (
    COUNTRY_ID number(5)  NOT NULL,
    STATE_ID number(5)  NOT NULL,
    STATE_NAME varchar2(50)  NOT NULL,
    CONSTRAINT Z_STATE_NAME_UK UNIQUE (COUNTRY_ID, STATE_NAME),
    CONSTRAINT Z_STATE_pk PRIMARY KEY (COUNTRY_ID,STATE_ID)
) ;

-- foreign keys
-- Reference: Z_ALLERGY_PATIENT_FK (table: Z_PATIENT_ALLERGY)
ALTER TABLE Z_PATIENT_ALLERGY ADD CONSTRAINT Z_ALLERGY_PATIENT_FK
    FOREIGN KEY (PATIENT_ID)
    REFERENCES Z_PATIENT (PATIENT_ID);

-- Reference: Z_CITY_COUNTY_FK (table: Z_CITY)
ALTER TABLE Z_CITY ADD CONSTRAINT Z_CITY_COUNTY_FK
    FOREIGN KEY (COUNTRY_ID,STATE_ID,COUNTY_ID)
    REFERENCES Z_COUNTY (COUNTRY_ID,STATE_ID,COUNTY_ID);

-- Reference: Z_CITY_Z_STATE (table: Z_CITY)
ALTER TABLE Z_CITY ADD CONSTRAINT Z_CITY_Z_STATE
    FOREIGN KEY (COUNTRY_ID,STATE_ID)
    REFERENCES Z_STATE (COUNTRY_ID,STATE_ID);

-- Reference: Z_COUNTY_STATE_FK (table: Z_COUNTY)
ALTER TABLE Z_COUNTY ADD CONSTRAINT Z_COUNTY_STATE_FK
    FOREIGN KEY (COUNTRY_ID,STATE_ID)
    REFERENCES Z_STATE (COUNTRY_ID,STATE_ID);

-- Reference: Z_IMAGING_STUDY_PATIENT_FK (table: Z_PATIENT_IMAGING_STUDY)
ALTER TABLE Z_PATIENT_IMAGING_STUDY ADD CONSTRAINT Z_IMAGING_STUDY_PATIENT_FK
    FOREIGN KEY (PATIENT_ID)
    REFERENCES Z_PATIENT (PATIENT_ID);

-- Reference: Z_IMMUNIZATION_PATIENT_FK (table: Z_PATIENT_IMMUNIZATION)
ALTER TABLE Z_PATIENT_IMMUNIZATION ADD CONSTRAINT Z_IMMUNIZATION_PATIENT_FK
    FOREIGN KEY (PATIENT_ID)
    REFERENCES Z_PATIENT (PATIENT_ID);

-- Reference: Z_PATIENT_ALLERGY_FK (table: Z_PATIENT_ALLERGY)
ALTER TABLE Z_PATIENT_ALLERGY ADD CONSTRAINT Z_PATIENT_ALLERGY_FK
    FOREIGN KEY (ALLERGY_CODE)
    REFERENCES Z_ALLERGY (ALLERGY_CODE);

-- Reference: Z_PATIENT_BIRTH_PLACE_FK (table: Z_PATIENT)
ALTER TABLE Z_PATIENT ADD CONSTRAINT Z_PATIENT_BIRTH_PLACE_FK
    FOREIGN KEY (BIRTH_PLACE_COUNTRY_ID,BIRTH_PLACE_STATE_ID,BIRTH_PLACE_CITY_ID)
    REFERENCES Z_CITY (COUNTRY_ID,STATE_ID,CITY_ID);

-- Reference: Z_PATIENT_BODYSITE_FK (table: Z_PATIENT_IMAGING_STUDY)
ALTER TABLE Z_PATIENT_IMAGING_STUDY ADD CONSTRAINT Z_PATIENT_BODYSITE_FK
    FOREIGN KEY (BODYSITE_CODE)
    REFERENCES Z_BODYSITE (BODYSITE_CODE);

-- Reference: Z_PATIENT_ETHNICITY_FK (table: Z_PATIENT)
ALTER TABLE Z_PATIENT ADD CONSTRAINT Z_PATIENT_ETHNICITY_FK
    FOREIGN KEY (ETHNICITY_ID)
    REFERENCES Z_ETHNICITY (ETHNICITY_ID);

-- Reference: Z_PATIENT_GENDER_FK (table: Z_PATIENT)
ALTER TABLE Z_PATIENT ADD CONSTRAINT Z_PATIENT_GENDER_FK
    FOREIGN KEY (GENDER_ID)
    REFERENCES Z_GENDER (GENDER_ID);

-- Reference: Z_PATIENT_IMMUNIZATION_FK (table: Z_PATIENT_IMMUNIZATION)
ALTER TABLE Z_PATIENT_IMMUNIZATION ADD CONSTRAINT Z_PATIENT_IMMUNIZATION_FK
    FOREIGN KEY (IMMUNIZATION_CODE)
    REFERENCES Z_IMMUNIZATION (IMMUNIZATION_CODE);

-- Reference: Z_PATIENT_LIVING_PLACE_FK (table: Z_PATIENT)
ALTER TABLE Z_PATIENT ADD CONSTRAINT Z_PATIENT_LIVING_PLACE_FK
    FOREIGN KEY (LIVING_PLACE_COUNTRY_ID,LIVING_PLACE_STATE_ID,LIVING_PLACE_CITY_ID)
    REFERENCES Z_CITY (COUNTRY_ID,STATE_ID,CITY_ID);

-- Reference: Z_PATIENT_MARITAL_STATUS_FK (table: Z_PATIENT)
ALTER TABLE Z_PATIENT ADD CONSTRAINT Z_PATIENT_MARITAL_STATUS_FK
    FOREIGN KEY (MARITAL_STATUS_ID)
    REFERENCES Z_MARITAL_STATUS (MARITAL_STATUS_ID);

-- Reference: Z_PATIENT_MODALITY_FK (table: Z_PATIENT_IMAGING_STUDY)
ALTER TABLE Z_PATIENT_IMAGING_STUDY ADD CONSTRAINT Z_PATIENT_MODALITY_FK
    FOREIGN KEY (MODALITY_CODE)
    REFERENCES Z_MODALITY (MODALITY_CODE);

-- Reference: Z_PATIENT_RACE_FK (table: Z_PATIENT)
ALTER TABLE Z_PATIENT ADD CONSTRAINT Z_PATIENT_RACE_FK
    FOREIGN KEY (RACE_ID)
    REFERENCES Z_RACE (RACE_ID);

-- Reference: Z_PATIENT_SOP_FK (table: Z_PATIENT_IMAGING_STUDY)
ALTER TABLE Z_PATIENT_IMAGING_STUDY ADD CONSTRAINT Z_PATIENT_SOP_FK
    FOREIGN KEY (SOP_CODE)
    REFERENCES Z_SOP (SOP_CODE);

-- Reference: Z_STATE_COUTRY_FK (table: Z_STATE)
ALTER TABLE Z_STATE ADD CONSTRAINT Z_STATE_COUTRY_FK
    FOREIGN KEY (COUNTRY_ID)
    REFERENCES Z_COUNTRY (COUNTRY_ID);

-- End of file.

